### ISSUE TITLE
No inference of type in nested Option

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [pjfanning/jackson-scala-reflect-extensions#5]
We were trying to use this library but we noticed that when an Option[Long] is located inside a case class nested in an Option, the module does not succeed to infer the type, giving Some(Integer) instead of Some(Long).

You can see the associated test case in the following PR : https://github.com/pjfanning/jackson-scala-reflect-extensions/pull/4

Yours faithfully,
LCDP

**Comment by pjfanning** [comment]
The FAQ entry linked in the project [readme](https://github.com/pjfanning/jackson-scala-reflect-extensions) describes some workarounds.

**Comment by AntoineDuComptoirDesPharmacies** [comment]
@pjfanning 
Of course, if we use the @JsonDeserialize  annotation, deserialization is going well.
But in our particular case, we are not able to modify the source case class and had hope to use this extension instead of writing a custom Bean deserializer.

EDIT :
O.K, we succeeded to make it work adding this sentence : 
    `ScalaAnnotationIntrospectorModule.registerReferencedValueType(classOf[NestedLong], "id", classOf[Long])`

That could make a good Workaround until extension manage this use case.

**Comment by pjfanning** [comment]
@AntoineDuComptoirDesPharmacies One thing I notice about your test cases (in your PR) is that they use vars instead of vals. I have similar classes that have vals instead of vars and the tests for those seem to work. You have a workaround already but I thought I'd pass on this observation.

**Comment by AntoineDuComptoirDesPharmacies** [comment]
@pjfanning I tried to put `val` instead of `var` but it seems that test still fail, I have the same behavior, `Long` is deserialized as `Integer`.

The workaround is working well. It just doesn't work when `Option` have a default `None` value.
See : https://github.com/FasterXML/jackson-module-scala/issues/598

**Comment by pjfanning** [comment]
@AntoineDuComptoirDesPharmacies I have your tests passing now. Needed a fix in jackson-module-scala so current main branch needs that snapshot version. There is also a fix in jackson-scala-reflect-extensions for a 2nd issue.

**Comment by pjfanning** [comment]
v2.13.4 is released.

**Comment by AntoineDuComptoirDesPharmacies** [comment]
@pjfanning 
v2.13.4 is working like a charm, thank you !
