### ISSUE TITLE
Fix loading form ClassLoader in specific contexts

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [pjfanning/jackson-scala-reflect-extensions#7]
We notice that we receive a ClassNotFoudException while using this library in a development Play Environnement.
This issue have already been hit in multiple library using the `Class.forName` method. (See : https://github.com/playframework/playframework/issues/6207)

The fix consist of using currentThread class loader while searching for class in classpath.
Example with the fix in Kafka library here : 
https://issues.apache.org/jira/browse/KAFKA-2295

You will find here a PR that fix the problem for this library : https://github.com/pjfanning/jackson-scala-reflect-extensions/pull/6

Yours faithfully,
LCDP

**Comment by pjfanning** [comment]
PR is merged
